# # # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# # name: Scrape Job Notifications

# # on:
# #   schedule:
# #     - cron: "0 1,12 * * *"
# #   push:
# #     branches: [ main ]

# # permissions:
# #   contents: write

# # jobs:
# #   scrape:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout repository
# #         uses: actions/checkout@v2
# #       - name: Set up Python 3.10
# #         uses: actions/setup-python@v2
# #         with:
# #           python-version: "3.10"
# #       - name: Cache dependencies
# #         uses: actions/cache@v2
# #         with:
# #           path: ~/.cache/pip
# #           key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
# #           restore-keys: |
# #             ${{ runner.os }}-pip-
# #       - name: Install dependencies
# #         run: |
# #           python -m pip install --upgrade pip
# #           pip install beautifulsoup4 requests
# #       - name: Cache jobs.json
# #         uses: actions/cache@v2
# #         with:
# #           path: jobs.json
# #           key: ${{ runner.os }}-jobs-json-${{ github.sha }}
# #           restore-keys: |
# #             ${{ runner.os }}-jobs-json-
# #       - name: Scrape job notifications
# #         run: python frontlines.py
# #       - name: Commit changes
# #         run: |
# #           git config --global user.email "action@github.com"
# #           git config --global user.name "GitHub Action"
# #           git add -u jobs.json
# #           git commit -m "Update job notifications"
# #           git push origin HEAD:main

# name: Scrape Job Notifications

# on:
#   schedule:
#     - cron: "0 1,12 * * *"
#   push:
#     branches: [ main ]

# permissions:
#   contents: write

# jobs:
#   scrape:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Python 3.10
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"

#       - name: Cache Python dependencies
#         uses: actions/cache@v3
#         with:
#           path: ~/.cache/pip
#           key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
#           restore-keys: |
#             ${{ runner.os }}-pip-

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Cache scraped jobs data
#         uses: actions/cache@v3
#         with:
#           path: jobs.json
#           key: ${{ runner.os }}-jobs-json-${{ github.sha }}
#           restore-keys: |
#             ${{ runner.os }}-jobs-json-

#       - name: Scrape job notifications
#         run: |
#           python frontlines.py
#         env:
#           DISPLAY: ":99"  # Optional, if running Selenium with GUI testing

#       - name: Commit and push changes
#         run: |
#           git config --global user.email "action@github.com"
#           git config --global user.name "GitHub Action"
#           git add jobs.json
#           git commit -m "Update job notifications"
#           git push origin HEAD:main


name: Scrape Job Notifications

on:
  schedule:
    - cron: "0 1,12 * * *"
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chromium and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install xvfb
        run: |
          sudo apt-get install -y xvfb

      - name: Cache scraped jobs data
        uses: actions/cache@v3
        with:
          path: jobs.json
          key: ${{ runner.os }}-jobs-json-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-jobs-json-

      - name: Scrape job notifications
        run: |
          xvfb-run -a python frontlines.py --browser headless-chrome
        env:
          DISPLAY: ":99"

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add jobs.json
          git commit -m "Update job notifications"
          git push origin HEAD:main
